name: flutter_toolkit_example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  adaptive_image:
    git:
      url: https://github.com/masa-tokyo/flutter_toolkit
      path: packages/adaptive_image
      ref: adaptive_image/v1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/